---
title: "Status of Acfrs data collection 2020 vs. 2021"
output: 
  html_document:
    toc: true
    toc_float: true
date: "2022-01-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 9, warning = FALSE, message = FALSE)
library(ggplot2)
library(tidyverse)
library(plotly)
```


# Entity Category

```{r}
db_2020 <- readRDS("data/data_from_dbsite.RDS")

db_2020 %>% 
select(category) %>% 
  group_by(category) %>% 
  add_count() %>% 
  rename("2020" = n) %>% 
  distinct() -> data_by_category_2020

db_2021 <- readRDS("data/data_from_dbsite_2021.RDS") # queried July

  db_2021 %>% select(category) %>% 
  group_by(category) %>% 
  add_count() %>% 
  rename("2021" = n) %>% 
  distinct() -> data_by_category_2021
  
  
data_count <- data_by_category_2020 %>% left_join(data_by_category_2021)
  
data_count %>% 
  pivot_longer(cols = 2:3,
               names_to = "year",
               values_to = "value") %>% 
  
  ggplot(aes(fct_reorder(category, value), value, group = year, fill = year)) +
  
  geom_col(position = "dodge",  alpha = .5) +
  
  coord_flip() +
  scale_alpha_continuous()+
  
  labs( x = "",
    title = paste0("Count of Entity by Category\n Total # 2020: ",
                  nrow(db_2020), " ~ 2021:", nrow(db_2021)), "\n",
    
    caption = "Data queried on Jan 4, 2023"
  ) +
  
  theme_minimal() -> p
ggplotly(p)
```


## School District by State

```{r}
# db_2021 %>% filter(category == "School District") %>%
#   group_by(state) %>%
#   add_count() %>%
#   ggplot(aes(fct_reorder(state, n))) +
# 
#   geom_bar(fill = "orange", alpha = .4) +
# 
#   coord_flip() +
# 
# 
#   labs( x = "",
#     title = "Count of School District by State",
#     subtitle = "Total of School District in Acfrs 2021: 9278",
#     caption = "Data queried on Jan 4, 2023"
#   ) +
# 
#   theme_minimal() -> p1
#   ggplotly(p1)
```



```{r}
db_2021 %>% filter(category == "School District") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2021" = n) %>% 
   distinct() -> schooldist_21

db_2020 %>% filter(category == "School District") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2020" = n) %>% 
   distinct() -> schooldist_20

schooldist_20 %>% left_join(schooldist_21) %>% 
  pivot_longer(cols = 2:3, names_to = "year", values_to = "value") %>% 

  ggplot(aes(fct_reorder(state, value), value, fill = year)) +
  geom_col(position = "dodge", alpha = .4) +
  coord_flip() +
  facet_wrap(~year) +
  labs( x = "",
    title = paste0("Count of School District by State 2020: ", sum(schooldist_20$`2020`), " ~ 2021:", sum(schooldist_21$`2021`)), 
   
    caption = "Data queried on Jan 4, 2023"
  ) +
  
  theme_minimal() -> p1


ggplotly(p1)
```

## General Purpose Entity by State


```{r}
db_2021 %>% filter(category == "General Purpose") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2021" = n) %>% 
   distinct() -> general_21

db_2020 %>% filter(category == "General Purpose") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2020" = n) %>% 
   distinct() -> general_20

general_20 %>% left_join(general_21) %>% 
  pivot_longer(cols = 2:3, names_to = "year", values_to = "value") %>% 

  ggplot(aes(fct_reorder(state, value), value, fill = year)) +
  geom_col(position = "dodge", alpha = .4) +
  coord_flip() +
  facet_wrap(~year) +
  labs( x = "",
   
    title = paste0("Count of General Purpose Entity by State 2020: ", sum(general_20$`2020`), " ~ 2021:", sum(general_21$`2021`)),
    caption = "Data queried on Jan 4, 2023"
  ) +
  
  theme_minimal() -> p2
ggplotly(p2)
```

## Special District by State

```{r}
db_2021 %>% filter(category == "Special District") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2021" = n) %>% 
   distinct() -> special_dist_21

db_2020 %>% filter(category == "Special District") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2020" = n) %>% 
   distinct() -> special_dist_20

special_dist_20 %>% left_join(special_dist_21) %>% 
  pivot_longer(cols = 2:3, names_to = "year", values_to = "value") %>% 

  ggplot(aes(fct_reorder(state, value), value, fill = year)) +
  geom_col(position = "dodge", alpha = .4) +
  coord_flip() +
  facet_wrap(~year) +
  labs( x = "",
    title = paste0("Count of Special District by State 2020: ", sum(special_dist_20$`2020`), " ~ 2021:", sum(special_dist_21$`2021`)),
    caption = "Data queried on Jan 4, 2023"
  ) +
  
  theme_minimal() -> p3
ggplotly(p3)
```


## Charter School by State

```{r}
db_2021 %>% filter(category == "Charter School") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2021" = n) %>% 
   distinct() -> charter_21

db_2020 %>% filter(category == "Charter School") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2020" = n) %>% 
   distinct() -> charter_20

charter_20 %>% left_join(charter_21) %>% 
  pivot_longer(cols = 2:3, names_to = "year", values_to = "value") %>% 

  ggplot(aes(fct_reorder(state, value), value, fill = year)) +
  geom_col(position = "dodge", alpha = .4) +
  coord_flip() +
  facet_wrap(~year) +
  labs( x = "",
    title = paste0("Count of Charter School by State 2020: ", sum(charter_20$`2020`), " ~ 2021:", sum(charter_21$`2021`)),
    caption = "Data queried on Jan 4, 2022"
  ) +
  
  theme_minimal() -> p4
ggplotly(p4)
```


## Community College District by State

```{r}
db_2021 %>% 
  filter(category == "Community College District") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2021" = n) %>% 
   distinct() -> com_col_21

db_2020 %>% filter(category == "Community College District") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2020" = n) %>% 
   distinct() -> com_col_20

com_col_20 %>% left_join(com_col_21) %>% 
  pivot_longer(cols = 2:3, names_to = "year", values_to = "value") %>% 

  ggplot(aes(fct_reorder(state, value), value, fill = year)) +
  geom_col(position = "dodge", alpha = .4) +
  coord_flip() +
  facet_wrap(~year) +
  labs( x = "",
  
    title = paste0("Count of Community College District by State 2020: ", sum(com_col_20$`2020`), " ~ 2021:", sum(com_col_21$`2021`)),
    caption = "Data queried on Jan 4, 2022"
  ) +
  
  theme_minimal() -> p5
ggplotly(p5)

```

## Public Higher Education by State

```{r}
db_2021 %>% 
  filter(category == "Public Higher Education") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2021" = n) %>% 
   distinct() -> pub_highed_21

db_2020 %>% filter(category == "Public Higher Education") %>% 
  group_by(state) %>% 
  add_count() %>% select(state, n) %>% 
  rename("2020" = n) %>% 
   distinct() -> pub_highed_20

pub_highed_20 %>% left_join(pub_highed_21) %>% 
  pivot_longer(cols = 2:3, names_to = "year", values_to = "value") %>% 

  ggplot(aes(fct_reorder(state, value), value, fill = year)) +
  geom_col(position = "dodge", alpha = .4) +
  coord_flip() +
  facet_wrap(~year) +
  labs( x = "",
   # title = "Count of Public Higher Education by State",
     title = paste0("Count of Public Higher Education by State 2020: ", sum(pub_highed_20$`2020`), " ~ 2021:", sum(pub_highed_21$`2021`)),
    caption = "Data queried on Jan 4, 2022"
  ) +
  
  theme_minimal() -> p6
ggplotly(p6)

```



