---
title: "Untitled"
output: html_document
date: "2023-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyr)
library(janitor)
library(plotly)
options(scipen = 999)
```

```{r}
sd2020_db <- readRDS("data/data_from_dbsite_2020.RDS") %>% 
  filter(category == "School District") %>% 
  mutate(id = as.character(id)) %>% 
  select(state, name,id, total_liabilities) %>% 
  rename(acfrs_original_name = name)

sd2020_namematched_Hgarb <- rio::import("data/_K12 School District 12_01_22 - Consolidated.csv") %>% 
  select(-c(Comments, `Employer name in GASB 68/ACFR`, `V13`)) %>% 
  rename(ncesID = `NCES ID`) %>% 
  mutate(ncesID = as.character(ncesID)) %>% 
  
    # removing a total line at bottom
  filter(`School District (Portal Name)` != "Totals") %>% 
  
  # CA -WHY REMOVING leading 0?
#mutate(ncesID = ifelse(State == "CA", gsub("^0", "", ncesID), ncesID)) %>% 
  
  # removing "," in numbers
    mutate(`Net Pension Liability` = str_replace_all(`Net Pension Liability`, ",", "")) %>% 
    mutate(`Net Pension Liability` = as.double(`Net Pension Liability`)) %>% 
  
  mutate(`Net Pension Asset` = str_replace_all(`Net Pension Asset`, ",", ""), 
         `Overall Liability (Asset) Associated with District Staff` = str_replace_all(`Overall Liability (Asset) Associated with District Staff`, ",", "")) %>% 
  
  # converting char to number
    mutate(`Net Pension Asset` = as.double(`Net Pension Asset`), 
           `Overall Liability (Asset) Associated with District Staff` = as.double(`Overall Liability (Asset) Associated with District Staff`)) %>% 


 # for sd collected ID that has only 6 digits, adding a leading 0
  mutate(ncesID = ifelse(str_length(ncesID) < 7, paste0("0", ncesID), ncesID)) %>% 

# special cases 
 mutate(ncesID = ifelse(ncesID == "4833090", "4833120", ncesID)) %>% # Hgarb attributed wrong NCES ID to this entity --> its nces ID should be 4833120
 select(ncesID, State, `School District (Portal Name)`, `Net Pension Liability`)

sd2020_namematched_Hgarb <- sd2020_namematched_Hgarb %>% 
  rename(state = State, 
         acfrs_original_name = `School District (Portal Name)`)

sd2020_db %>% select(-4) %>% write.csv("sd_acfrs_2020.csv")
sd2021_db %>% select(1:4) %>% write.csv("sd_acfrs_2021.csv")

sd2020_db %>% left_join()
```



```{r}
# those in HGarb but not in db 
sd2020_namematched_Hgarb %>% left_join(sd2020_db) %>% filter(is.na(id)) %>% 
  left_join(nces) %>% arrange(desc(students)) %>% filter(students > 300) 
  filter(state == "IL")
  
 sd2020_namematched_Hgarb %>% filter(is.na(ncesID))
 
 nces %>% filter(str_detect(nces_original_name, "(?i)Bergenfield"))
 
 # among Hgarb already collected. how many students?
 sd2020_namematched_Hgarb %>% filter(!is.na(ncesID)) %>% 
   left_join(nces, by = "ncesID") %>% filter(is.na(students)) -> t
 
sum(t$students, na.rm = T)

t %>% select(ncesID, state.x, acfrs_original_name, students) %>% arrange(desc(students)) %>% filter(students > 500)
  #filter(students < 500) %>%  # 1571 sd with less than 300 students, total 241907 students OR # 2443 sd less than 500 students, total 588437 students
  #mutate(tot = sum(students)) 

sd2020_namematched_Hgarb %>% left_join(nces, by = "ncesID") %>% filter(is.na(nces_original_name))

nces %>% left_join(sd2020_namematched_Hgarb, by = "ncesID") %>% filter(is.na(nces_original_name))

# those in nces but not in dictionary: 2998
setdiff(nces$ncesID, dictionary$ncesID) -> missing_ncesID
length(missing_ncesID)

# those in dictionary with both ncesID and acfrs id: 8403
dictionary %>% filter(!is.na(id)) -> dic_withid
dic_withid %>% filter(is.na(ncesID))

# those in nces with OUT acfrs id: 5319 + with acfrs id 8403 = 13722
nces %>% left_join(dic_withid, by = "ncesID") %>% 
  filter(is.na(id)) %>% 
  
  # only need those > 1000 students : 1426
  filter(students > 1000) %>% 
  
  # # no need for 33 that already manually collected 
   filter(nces_original_name != "Davidson County") %>% 
   filter(!str_detect(nces_original_name, "(NEW YORK CITY GEOGRAPHIC DISTRICT)")) %>% 
  
  arrange(desc(students)) %>% 
  select(-c(name, state.y)) %>% 
  rename(state = state.x) -> missing_nces_morethan_1000

write.csv(missing_nces_morethan_1000, "missing_nces_morethan_1000.csv")

# Who is this list off 1426 are already in acfrs? if yes, paste acfrs id in, those who are not, can we find? 

# need to fill acfrs id in these. total 6,913,291 students
missing_nces_morethan_1000 %>% mutate(tot = sum(students))

# total already have both ncesID and acfrs id: 40192764 students
nces %>% left_join(dic_withid, by = "ncesID") %>% drop_na(id) %>% mutate(tot = sum(students)) 

# what sd 2020 left with out nces ID? 
sd2020_db %>% left_join(dic_withid) %>% filter(is.na(ncesID)) -> need_nces_2020

# what sd 2021 left with out nces ID? 
sd2021_db %>% 
  rename(acfrs_original_name = name) %>% 
  left_join(dic_withid) %>% filter(is.na(ncesID)) %>% 
  select(state, acfrs_original_name, id, ncesID) %>% 
  rename(acfrsID = id) -> need_nces_2021

# any in 2020 that are not already in 2021? 
need_nces_2020 %>% filter(!id %in% need_nces_2021$id) %>% 
  rename(acfrsID = id) %>% 
  select(-c(total_liabilities, name)) -> id2020_not_in_2021

# rbind these 222 into need nces 2021: These have acfrsID --> 3808 need to add ncesID
need_nces_2021 %>% rbind(id2020_not_in_2021) %>% write.csv("sd_in_acfrs_need_ncesID.csv")

```



